export type Allergenes = {
  gluten: boolean;
  crustaces: boolean;
  oeufs: boolean;
  poisson: boolean;
  arachides: boolean;
  soja: boolean;
  lait: boolean;
  fruitsACoque: boolean;
  celeri: boolean;
  moutarde: boolean;
  sesame: boolean;
  sulfites: boolean;
  lupin: boolean;
  mollusques: boolean;
};

export type InformationsNutritionnelles = {
  valeursPour: "100 g";
  energieKj: number;
  caloriesKcal: number;
  matieresGrassesG: number;
  acidesGrasSaturesG: number;
  glucidesG: number;
  sucresG: number;
  fibresG: number;
  proteinesG: number;
  selG: number;
};

export const labelsAllergenes: Record<keyof Allergenes, string> = {
  gluten: "Gluten",
  crustaces: "Crustacés",
  oeufs: "Œufs",
  poisson: "Poisson",
  arachides: "Arachides",
  soja: "Soja",
  lait: "Lait",
  fruitsACoque: "Fruits à coque",
  celeri: "Céleri",
  moutarde: "Moutarde",
  sesame: "Graines de sésame",
  sulfites: "Sulfites",
  lupin: "Lupin",
  mollusques: "Mollusques",
};

type PlatBase = {
  name: string;
  categorie: "Pizza" | "Salade" | "Dessert";
  image: string;
  bestsellers: boolean;
  allergenes: Allergenes;
  nutrition: InformationsNutritionnelles;
};

type Pizza = PlatBase & {
  type: "pizza";
  prices: {
    junior: number | null;
    senior: number | null;
    mega: number | null;
  };
};

type PlatSimple = PlatBase & {
  type: "salade" | "dessert";
  description?: string;
  price: number | null;
};

export const pizza: Pizza[] = [
  {
    name: "CLASSICA",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: true,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1004,
      caloriesKcal: 240,
      matieresGrassesG: 8.5,
      acidesGrasSaturesG: 3.8,
      glucidesG: 30,
      sucresG: 3.2,
      fibresG: 2.1,
      proteinesG: 10.5,
      selG: 1.3,
    },
    prices: { junior: 8.0, senior: 10.0, mega: 15.0 },
  },
  {
    name: "REGINA",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: true,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1088,
      caloriesKcal: 260,
      matieresGrassesG: 10.8,
      acidesGrasSaturesG: 4.5,
      glucidesG: 28.5,
      sucresG: 2.9,
      fibresG: 1.9,
      proteinesG: 12.4,
      selG: 1.5,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "SICILIENNE",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: true,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: true,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1059,
      caloriesKcal: 253,
      matieresGrassesG: 10.2,
      acidesGrasSaturesG: 3.7,
      glucidesG: 29.1,
      sucresG: 3.1,
      fibresG: 2.4,
      proteinesG: 11.8,
      selG: 1.7,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "CALZONE (soufflée)",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: true,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1130,
      caloriesKcal: 270,
      matieresGrassesG: 11.6,
      acidesGrasSaturesG: 5.1,
      glucidesG: 29.8,
      sucresG: 3.4,
      fibresG: 1.8,
      proteinesG: 12.1,
      selG: 1.4,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "ORIENTALE",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: true,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: true,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1172,
      caloriesKcal: 280,
      matieresGrassesG: 12.9,
      acidesGrasSaturesG: 5.3,
      glucidesG: 28.2,
      sucresG: 3,
      fibresG: 2.2,
      proteinesG: 13,
      selG: 1.8,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "4 SAISONS",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: true,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 971,
      caloriesKcal: 232,
      matieresGrassesG: 8.1,
      acidesGrasSaturesG: 3.6,
      glucidesG: 29.4,
      sucresG: 3.6,
      fibresG: 2.8,
      proteinesG: 9.7,
      selG: 1.2,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "PAYSANNE",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: true,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: true,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1205,
      caloriesKcal: 288,
      matieresGrassesG: 14.1,
      acidesGrasSaturesG: 6.2,
      glucidesG: 27.5,
      sucresG: 2.7,
      fibresG: 1.7,
      proteinesG: 13.4,
      selG: 1.7,
    },
    prices: { junior: 9.5, senior: 13.0, mega: 18.0 },
  },
  {
    name: "RIMINI",
    categorie: "Pizza",
    type: "pizza",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: true,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: true,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1021,
      caloriesKcal: 244,
      matieresGrassesG: 9.4,
      acidesGrasSaturesG: 4,
      glucidesG: 28.7,
      sucresG: 2.8,
      fibresG: 1.9,
      proteinesG: 11.6,
      selG: 1.6,
    },
    prices: { junior: 9.5, senior: 13.5, mega: null },
  },
];

export const salades: PlatSimple[] = [
  {
    name: "PALERMO",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description:
      "Salade de saison, tomates fraîches, poivrons grillés, artichauts, mozzarella",
    allergenes: {
      gluten: false,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 435,
      caloriesKcal: 104,
      matieresGrassesG: 6.7,
      acidesGrasSaturesG: 3.1,
      glucidesG: 5.4,
      sucresG: 3.6,
      fibresG: 2,
      proteinesG: 5.2,
      selG: 0.8,
    },
    price: 8.0,
  },
  {
    name: "PARIGI",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description: "Salade de saison, tomates fraîches, jambon, champignons",
    allergenes: {
      gluten: false,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: false,
      fruitsACoque: false,
      celeri: true,
      moutarde: true,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 347,
      caloriesKcal: 83,
      matieresGrassesG: 3.8,
      acidesGrasSaturesG: 1.2,
      glucidesG: 4.6,
      sucresG: 2.5,
      fibresG: 1.6,
      proteinesG: 7.2,
      selG: 1,
    },
    price: 8.0,
  },
  {
    name: "ITALIENNE",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description: "Salade de saison, tomates fraîches, thon, œuf dur, olives",
    allergenes: {
      gluten: false,
      crustaces: false,
      oeufs: true,
      poisson: true,
      arachides: false,
      soja: false,
      lait: false,
      fruitsACoque: false,
      celeri: false,
      moutarde: true,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 527,
      caloriesKcal: 126,
      matieresGrassesG: 7.1,
      acidesGrasSaturesG: 1.5,
      glucidesG: 4.2,
      sucresG: 2.4,
      fibresG: 1.5,
      proteinesG: 11.2,
      selG: 1.1,
    },
    price: 8.0,
  },
  {
    name: "FERMIÈRE",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description: "Salade de saison, tomates fraîches, poulet, maïs",
    allergenes: {
      gluten: false,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: true,
      lait: false,
      fruitsACoque: false,
      celeri: true,
      moutarde: true,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 452,
      caloriesKcal: 108,
      matieresGrassesG: 4.1,
      acidesGrasSaturesG: 0.9,
      glucidesG: 7.3,
      sucresG: 3.1,
      fibresG: 1.7,
      proteinesG: 10.1,
      selG: 0.7,
    },
    price: 8.0,
  },
  {
    name: "CHAVIGNOL",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description:
      "Salade de saison, tomates fraîches, crottin en toast, lardons",
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: false,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: true,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 732,
      caloriesKcal: 175,
      matieresGrassesG: 11.9,
      acidesGrasSaturesG: 5.7,
      glucidesG: 7.8,
      sucresG: 2.1,
      fibresG: 1.4,
      proteinesG: 9.5,
      selG: 1.3,
    },
    price: 8.0,
  },
  {
    name: "NORVÉGIENNE",
    categorie: "Salade",
    type: "salade",
    image: "",
    bestsellers: false,
    description:
      "Salade de saison, tomates fraîches, crevettes, saumon fumé",
    allergenes: {
      gluten: false,
      crustaces: true,
      oeufs: false,
      poisson: true,
      arachides: false,
      soja: false,
      lait: false,
      fruitsACoque: false,
      celeri: false,
      moutarde: true,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 498,
      caloriesKcal: 119,
      matieresGrassesG: 6.3,
      acidesGrasSaturesG: 1.3,
      glucidesG: 3.9,
      sucresG: 2,
      fibresG: 1.3,
      proteinesG: 12.4,
      selG: 1.8,
    },
    price: 8.0,
  },
];

export const desserts: PlatSimple[] = [
  {
    name: "TARTE AU DAIM",
    categorie: "Dessert",
    type: "dessert",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: true,
      poisson: false,
      arachides: false,
      soja: true,
      lait: true,
      fruitsACoque: true,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1724,
      caloriesKcal: 412,
      matieresGrassesG: 24.5,
      acidesGrasSaturesG: 13.2,
      glucidesG: 42.1,
      sucresG: 29.8,
      fibresG: 2.2,
      proteinesG: 5.8,
      selG: 0.5,
    },
    price: null,
  },
  {
    name: "BROWNIE",
    categorie: "Dessert",
    type: "dessert",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: true,
      poisson: false,
      arachides: false,
      soja: true,
      lait: true,
      fruitsACoque: true,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: false,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1870,
      caloriesKcal: 447,
      matieresGrassesG: 26.2,
      acidesGrasSaturesG: 11.4,
      glucidesG: 45.7,
      sucresG: 31.5,
      fibresG: 3.1,
      proteinesG: 6.4,
      selG: 0.4,
    },
    price: null,
  },
  {
    name: "TIRAMISU",
    categorie: "Dessert",
    type: "dessert",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: true,
      poisson: false,
      arachides: false,
      soja: true,
      lait: true,
      fruitsACoque: false,
      celeri: false,
      moutarde: false,
      sesame: false,
      sulfites: true,
      lupin: false,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1255,
      caloriesKcal: 300,
      matieresGrassesG: 18.1,
      acidesGrasSaturesG: 10.7,
      glucidesG: 28.4,
      sucresG: 20.2,
      fibresG: 0.8,
      proteinesG: 5.9,
      selG: 0.3,
    },
    price: null,
  },
  {
    name: "PANINI NUTELLA",
    categorie: "Dessert",
    type: "dessert",
    image: "",
    bestsellers: false,
    allergenes: {
      gluten: true,
      crustaces: false,
      oeufs: false,
      poisson: false,
      arachides: false,
      soja: true,
      lait: true,
      fruitsACoque: true,
      celeri: false,
      moutarde: false,
      sesame: true,
      sulfites: false,
      lupin: true,
      mollusques: false,
    },
    nutrition: {
      valeursPour: "100 g",
      energieKj: 1594,
      caloriesKcal: 381,
      matieresGrassesG: 17.6,
      acidesGrasSaturesG: 7.4,
      glucidesG: 48.9,
      sucresG: 23.7,
      fibresG: 3,
      proteinesG: 8.1,
      selG: 0.8,
    },
    price: null,
  },
];
